/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "hexlet"
version = "1.0-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

plugins {
    id("java")
    id("application")
    id("checkstyle")
    id("jvm-test-suite")
    id("com.github.ben-manes.versions") version "0.53.0"
    id("io.freefair.lombok") version "9.1.0"
    id("se.patrikerdes.use-latest-versions") version "0.2.19"
    id("com.gradleup.shadow") version "9.3.0"
    id("org.sonarqube") version "7.2.2.6593"
    id("jacoco")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

checkstyle {
    toolVersion = "12.3.1"

    configFile = file("config/checkstyle/checkstyle.xml")

    isIgnoreFailures = true
    maxWarnings = 0
    maxErrors = 0
}

jacoco {
    toolVersion = "0.8.13"
}

sonar {
    properties {
        property("sonar.projectKey", "AnrDaemon_java-project-71")
        property("sonar.organization", "anrdaemon")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
    // https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    implementation("org.apache.commons:commons-lang3:3.20.0")
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.1")
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.20.1")

    // https://mvnrepository.com/artifact/info.picocli/picocli
    implementation("info.picocli:picocli:4.7.7")
    // https://mvnrepository.com/artifact/info.picocli/picocli-codegen
    annotationProcessor("info.picocli:picocli-codegen:4.7.7")
}

application {
    // Define the main class for the application.
    mainClass.set("hexlet.code.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to application.mainClass.get(),
            "Implementation-Title" to "Diff calculator course work",
            "Implementation-Version" to project.version
        )
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(arrayOf(
        "-Aproject=${project.group}/${project.name}"
    ))
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        csv.required.set(false)
    }
}

tasks.register("install") {
    dependsOn("installShadowDist")
}
